// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tpLabo4_usarEste_.Models;

#nullable disable

namespace tpLabo4_usarEste_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221115212051_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("tpLabo4_usarEste_.Models.Celular", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("TiendaWEbid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("marcaId")
                        .HasColumnType("int");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.Property<int>("sistemaOperativoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("TiendaWEbid");

                    b.HasIndex("marcaId");

                    b.HasIndex("sistemaOperativoId");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("tpLabo4_usarEste_.Models.Marca", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("tpLabo4_usarEste_.Models.Proveedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Nombreproovedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TiendaWEbid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("TiendaWEbid");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("tpLabo4_usarEste_.Models.SistemaOperativo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SistemaOperativo");
                });

            modelBuilder.Entity("tpLabo4_usarEste_.Models.TiendaWEb", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nombreTienda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TiendaWEbs");
                });

            modelBuilder.Entity("tpLabo4_usarEste_.Models.Celular", b =>
                {
                    b.HasOne("tpLabo4_usarEste_.Models.TiendaWEb", null)
                        .WithMany("celulars")
                        .HasForeignKey("TiendaWEbid");

                    b.HasOne("tpLabo4_usarEste_.Models.Marca", "marca")
                        .WithMany()
                        .HasForeignKey("marcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tpLabo4_usarEste_.Models.SistemaOperativo", "SistemaOperativo")
                        .WithMany()
                        .HasForeignKey("sistemaOperativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SistemaOperativo");

                    b.Navigation("marca");
                });

            modelBuilder.Entity("tpLabo4_usarEste_.Models.Proveedor", b =>
                {
                    b.HasOne("tpLabo4_usarEste_.Models.TiendaWEb", null)
                        .WithMany("proveedors")
                        .HasForeignKey("TiendaWEbid");
                });

            modelBuilder.Entity("tpLabo4_usarEste_.Models.TiendaWEb", b =>
                {
                    b.Navigation("celulars");

                    b.Navigation("proveedors");
                });
#pragma warning restore 612, 618
        }
    }
}
